---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: crossplane-provider-k8s
  namespace: crossplane-system
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-kubernetes:v0.16.0
  runtimeConfigRef:
    name: crossplane-provider-k8s

---

apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: crossplane-provider-k8s
  namespace: crossplane-system
spec:
  serviceAccountTemplate:
    metadata:
      name: crossplane-provider-k8s

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crossplane-provider-k8s-cluster-admin
subjects:
  - kind: ServiceAccount
    name: crossplane-provider-k8s
    namespace: crossplane-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
