apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: service-first
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./services/first
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system