# flux HelmRelease crd for installing nginx ingress controller helm chart
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: crossplane
  namespace: crossplane-system
spec:
  releaseName: crossplane-system
  interval: 1h # this is for drifting of the helm created resources
  chart:
    spec:
      chart: crossplane
      version: "*"
      interval: 5h # this is for checking of a new chart
      sourceRef:
        kind: HelmRepository
        name: crossplane-stable
        namespace: crossplane-system
  
  