apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-ingress
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./components/nginx-ingress
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system