apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane-catalog
  namespace: flux-system
spec:
  dependsOn:
  - name: crossplane-core
  interval: 10m0s
  path: ./catalog
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system