apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crossplane-catalog
  namespace: flux-system
spec:
  dependsOn:
  - name: crossplane-core
  interval: 10m0s
  path: ./catalog
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: catalog
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: https://github.com/p-l-a-y-g-r-o-u-n-d/catalog.git

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: catalog-repository
  namespace: flux-system
spec:
  dependsOn:
  - name: crossplane-core
  interval: 10m0s
  path: .
  prune: true
  sourceRef:
    kind: GitRepository
    name: catalog
